/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {FilledSelect} from './FilledSelect';

const meta = {
  title: 'select/FilledSelect',
  component: FilledSelect,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onChange: action('change'),
    onInput: action('input'),
  },
  render: (args) => React.createElement(FilledSelect, args, "FilledSelect"),
};
