/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFilledSelect} from '@material/web/select/filled-select.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FilledSelectProps extends Omit<WebComponentProps<MdFilledSelect>, 'onChange' | 'onInput'> {
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
}

export const FilledSelect = createComponentTyped<MdFilledSelect, FilledSelectProps>({
  displayName: 'FilledSelect',
  tagName: 'md-filled-select',
  importPath: '@material/web/select/filled-select.js',
  importer: () => import('@material/web/select/filled-select.js'),
  events: {
  "change": "onChange",
  "input": "onInput"
},
});
