/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdOutlinedSelect} from '@material/web/select/outlined-select.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface OutlinedSelectProps extends Omit<WebComponentProps<MdOutlinedSelect>, 'onChange' | 'onInput'> {
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
}

export const OutlinedSelect = createComponentTyped<MdOutlinedSelect, OutlinedSelectProps>({
  displayName: 'OutlinedSelect',
  tagName: 'md-outlined-select',
  importPath: '@material/web/select/outlined-select.js',
  importer: () => import('@material/web/select/outlined-select.js'),
  events: {
  "change": "onChange",
  "input": "onInput"
},
});
