/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type * as React from 'react';
import {forwardRef} from 'react';

import type {MdOutlinedSelect} from '@material/web/select/outlined-select.js';

import type {WebComponentProps} from '../internal/createComponent';
import {useWebComponent} from '../internal/useWebComponent';

export interface OutlinedSelectProps
  extends Omit<
    WebComponentProps<MdOutlinedSelect>,
    'onChange' | 'onInput' | 'onOpening' | 'onOpened' | 'onClosing' | 'onClosed'
  > {
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
  onOpening?: (event: Event) => void;
  onOpened?: (event: Event) => void;
  onClosing?: (event: Event) => void;
  onClosed?: (event: Event) => void;
}

export const OutlinedSelect = forwardRef<MdOutlinedSelect, OutlinedSelectProps>(
  function OutlinedSelect(
    {children, onChange, onInput, onOpening, onOpened, onClosing, onClosed, ...rest},
    ref,
  ) {
    const {ref: mergedRef, domProps} = useWebComponent<MdOutlinedSelect>(
      {
        tagName: 'md-outlined-select',
        importer: () => import('@material/web/select/outlined-select.js'),
        events: {
          change: 'onChange',
          input: 'onInput',
          opening: 'onOpening',
          opened: 'onOpened',
          closing: 'onClosing',
          closed: 'onClosed',
        },
      },
      {onChange, onInput, onOpening, onOpened, onClosing, onClosed, ...rest},
      ref,
    );

    return (
      // eslint-disable-next-line react/no-unknown-property
      <md-outlined-select ref={mergedRef} {...domProps}>
        {children}
      </md-outlined-select>
    );
  },
);
