/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {SelectOption} from './SelectOption';

const meta = {
  title: 'select/SelectOption',
  component: SelectOption,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(SelectOption, args, "Option"),
};
