/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdSelectOption} from '@material/web/select/select-option.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface SelectOptionProps extends WebComponentProps<MdSelectOption> {}

export const SelectOption = createComponentTyped<MdSelectOption, SelectOptionProps>({
  displayName: 'SelectOption',
  tagName: 'md-select-option',
  importPath: '@material/web/select/select-option.js',
  importer: () => import('@material/web/select/select-option.js'),
  
});
