/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type * as React from 'react';
import {forwardRef} from 'react';

import type {MdSelectOption} from '@material/web/select/select-option.js';

import type {WebComponentProps} from '../internal/createComponent';
import {useWebComponent} from '../internal/useWebComponent';

export interface SelectOptionProps
  extends Omit<
    WebComponentProps<MdSelectOption>,
    'onCloseMenu' | 'onRequestSelection' | 'onRequestDeselection'
  > {
  onCloseMenu?: (event: Event) => void;
  onRequestSelection?: (event: Event) => void;
  onRequestDeselection?: (event: Event) => void;
}

export const SelectOption = forwardRef<MdSelectOption, SelectOptionProps>(
  function SelectOption(
    {children, onCloseMenu, onRequestSelection, onRequestDeselection, ...rest},
    ref,
  ) {
    const {ref: mergedRef, domProps} = useWebComponent<MdSelectOption>(
      {
        tagName: 'md-select-option',
        importer: () => import('@material/web/select/select-option.js'),
        events: {
          'close-menu': 'onCloseMenu',
          'request-selection': 'onRequestSelection',
          'request-deselection': 'onRequestDeselection',
        },
      },
      {onCloseMenu, onRequestSelection, onRequestDeselection, ...rest},
      ref,
    );

    return (
      // eslint-disable-next-line react/no-unknown-property
      <md-select-option ref={mergedRef} {...domProps}>
        {children}
      </md-select-option>
    );
  },
);
