/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdRipple} from '@material/web/ripple/ripple.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface RippleProps extends WebComponentProps<MdRipple> {}

export const Ripple = createComponentTyped<MdRipple, RippleProps>({
  displayName: 'Ripple',
  tagName: 'md-ripple',
  importPath: '@material/web/ripple/ripple.js',
  importer: () => import('@material/web/ripple/ripple.js'),
  
});
