/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdSwitch} from '@material/web/switch/switch.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface SwitchProps extends Omit<WebComponentProps<MdSwitch>, 'onChange' | 'onInput'> {
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
}

export const Switch = createComponentTyped<MdSwitch, SwitchProps>({
  displayName: 'Switch',
  tagName: 'md-switch',
  importPath: '@material/web/switch/switch.js',
  importer: () => import('@material/web/switch/switch.js'),
  events: {
  "change": "onChange",
  "input": "onInput"
},
});
