/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdSlider} from '@material/web/slider/slider.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface SliderProps extends Omit<WebComponentProps<MdSlider>, 'onChange' | 'onInput'> {
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
}

export const Slider = createComponentTyped<MdSlider, SliderProps>({
  displayName: 'Slider',
  tagName: 'md-slider',
  importPath: '@material/web/slider/slider.js',
  importer: () => import('@material/web/slider/slider.js'),
  events: {
  "change": "onChange",
  "input": "onInput"
},
});
