/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {AssistChip} from './AssistChip';

const meta = {
  title: 'chips/AssistChip',
  component: AssistChip,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(AssistChip, args, "Assist"),
};
