/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdAssistChip} from '@material/web/chips/assist-chip.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface AssistChipProps extends WebComponentProps<MdAssistChip> {}

export const AssistChip = createComponentTyped<MdAssistChip, AssistChipProps>({
  displayName: 'AssistChip',
  tagName: 'md-assist-chip',
  importPath: '@material/web/chips/assist-chip.js',
  importer: () => import('@material/web/chips/assist-chip.js'),
  
});
