/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdChipSet} from '@material/web/chips/chip-set.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface ChipSetProps extends WebComponentProps<MdChipSet> {}

export const ChipSet = createComponentTyped<MdChipSet, ChipSetProps>({
  displayName: 'ChipSet',
  tagName: 'md-chip-set',
  importPath: '@material/web/chips/chip-set.js',
  importer: () => import('@material/web/chips/chip-set.js'),
  
});
