/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {ChipSet} from './ChipSet';

const meta = {
  title: 'chips/ChipSet',
  component: ChipSet,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(ChipSet, args, "ChipSet"),
};
