/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {FilterChip} from './FilterChip';

const meta = {
  title: 'chips/FilterChip',
  component: FilterChip,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(FilterChip, args, "Filter"),
};
