/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFilterChip} from '@material/web/chips/filter-chip.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FilterChipProps extends WebComponentProps<MdFilterChip> {}

export const FilterChip = createComponentTyped<MdFilterChip, FilterChipProps>({
  displayName: 'FilterChip',
  tagName: 'md-filter-chip',
  importPath: '@material/web/chips/filter-chip.js',
  importer: () => import('@material/web/chips/filter-chip.js'),
  
});
