/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdInputChip} from '@material/web/chips/input-chip.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface InputChipProps extends WebComponentProps<MdInputChip> {}

export const InputChip = createComponentTyped<MdInputChip, InputChipProps>({
  displayName: 'InputChip',
  tagName: 'md-input-chip',
  importPath: '@material/web/chips/input-chip.js',
  importer: () => import('@material/web/chips/input-chip.js'),
  
});
