/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdSuggestionChip} from '@material/web/chips/suggestion-chip.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface SuggestionChipProps extends WebComponentProps<MdSuggestionChip> {}

export const SuggestionChip = createComponentTyped<MdSuggestionChip, SuggestionChipProps>({
  displayName: 'SuggestionChip',
  tagName: 'md-suggestion-chip',
  importPath: '@material/web/chips/suggestion-chip.js',
  importer: () => import('@material/web/chips/suggestion-chip.js'),
  
});
