/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {SuggestionChip} from './SuggestionChip';

const meta = {
  title: 'chips/SuggestionChip',
  component: SuggestionChip,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(SuggestionChip, args, "Suggestion"),
};
