/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdDialog} from '@material/web/dialog/dialog.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface DialogProps extends Omit<WebComponentProps<MdDialog>, 'onOpen' | 'onOpened' | 'onClose' | 'onClosed' | 'onCancel'> {
  onOpen?: (event: Event) => void;
  onOpened?: (event: Event) => void;
  onClose?: (event: Event) => void;
  onClosed?: (event: Event) => void;
  onCancel?: (event: Event) => void;
}

export const Dialog = createComponentTyped<MdDialog, DialogProps>({
  displayName: 'Dialog',
  tagName: 'md-dialog',
  importPath: '@material/web/dialog/dialog.js',
  importer: () => import('@material/web/dialog/dialog.js'),
  events: {
  "open": "onOpen",
  "opened": "onOpened",
  "close": "onClose",
  "closed": "onClosed",
  "cancel": "onCancel"
},
});
