/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {Dialog} from './Dialog';

const meta = {
  title: 'dialog/Dialog',
  component: Dialog,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onOpen: action('open'),
    onOpened: action('opened'),
    onClose: action('close'),
    onClosed: action('closed'),
    onCancel: action('cancel'),
  },
  render: (args: any) => React.createElement(Dialog, args, "Dialog content"),
};
