/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdBrandedFab} from '@material/web/fab/branded-fab.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface BrandedFabProps extends WebComponentProps<MdBrandedFab> {}

export const BrandedFab = createComponentTyped<MdBrandedFab, BrandedFabProps>({
  displayName: 'BrandedFab',
  tagName: 'md-branded-fab',
  importPath: '@material/web/fab/branded-fab.js',
  importer: () => import('@material/web/fab/branded-fab.js'),
  
});
