/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {BrandedFab} from './BrandedFab';

const GOOGLE_PLUS = (
  <svg slot="icon" viewBox="0 0 36 36" aria-hidden="true" width="36" height="36">
    <path fill="#34A853" d="M16 16v14h4V20z" />
    <path fill="#4285F4" d="M30 16H20l-4 4h14z" />
    <path fill="#FBBC05" d="M6 16v4h10l4-4z" />
    <path fill="#EA4335" d="M20 16V6h-4v14z" />
    <path fill="none" d="M0 0h36v36H0z" />
  </svg>
);

const meta = {
  title: 'fab/BrandedFab',
  component: BrandedFab,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
  argTypes: {
    size: {control: {type: 'select'}, options: ['medium', 'large']},
    label: {control: 'text'},
    lowered: {control: 'boolean'},
    touchTarget: {
      control: {type: 'select'},
      options: ['', 'wrapper', 'none'],
    },
  },
};

export default meta;

export const Default = {
  args: {
    size: 'medium',
    label: '',
    lowered: false,
    touchTarget: '',
    onClick: action('click'),
  },
  render: (args) => (
    <BrandedFab
      {...args}
      touchTarget={args.touchTarget ? args.touchTarget : undefined}
      aria-label={args.label ? args.label : 'Add'}
    >
      {GOOGLE_PLUS}
    </BrandedFab>
  ),
};
