/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFab} from '@material/web/fab/fab.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FabProps extends WebComponentProps<MdFab> {}

export const Fab = createComponentTyped<MdFab, FabProps>({
  displayName: 'Fab',
  tagName: 'md-fab',
  importPath: '@material/web/fab/fab.js',
  importer: () => import('@material/web/fab/fab.js'),
  
});
