/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {Fab} from './Fab';

const meta = {
  title: 'fab/Fab',
  component: Fab,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args: any) => React.createElement(Fab, args, "Edit"),
};
