/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFocusRing} from '@material/web/focus/md-focus-ring.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FocusRingProps extends WebComponentProps<MdFocusRing> {}

export const FocusRing = createComponentTyped<MdFocusRing, FocusRingProps>({
  displayName: 'FocusRing',
  tagName: 'md-focus-ring',
  importPath: '@material/web/focus/md-focus-ring.js',
  importer: () => import('@material/web/focus/md-focus-ring.js'),
  
});
