/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {FocusRing} from './FocusRing';

const meta = {
  title: 'focus/FocusRing',
  component: FocusRing,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => (
    <div style={{display: 'flex', gap: 16}}>
      <button
        type="button"
        style={{
          appearance: 'none',
          background: 'var(--md-sys-color-surface)',
          border: 'none',
          borderRadius: 16,
          height: 64,
          outline: 'none',
          position: 'relative',
          width: 64,
          ['--md-focus-ring-shape' as any]: '16px',
        }}
      >
        <FocusRing {...args} />
      </button>
      <button
        type="button"
        style={{
          appearance: 'none',
          background: 'var(--md-sys-color-surface)',
          border: 'none',
          borderRadius: 16,
          height: 64,
          outline: 'none',
          position: 'relative',
          width: 64,
          ['--md-focus-ring-shape' as any]: '16px',
        }}
      >
        <FocusRing {...args} />
      </button>
    </div>
  ),
};
