/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFilledIconButton} from '@material/web/iconbutton/filled-icon-button.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FilledIconButtonProps extends WebComponentProps<MdFilledIconButton> {}

export const FilledIconButton = createComponentTyped<MdFilledIconButton, FilledIconButtonProps>({
  displayName: 'FilledIconButton',
  tagName: 'md-filled-icon-button',
  importPath: '@material/web/iconbutton/filled-icon-button.js',
  importer: () => import('@material/web/iconbutton/filled-icon-button.js'),
  
});
