/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {FilledTonalIconButton} from './FilledTonalIconButton';

const meta = {
  title: 'icon-button/FilledTonalIconButton',
  component: FilledTonalIconButton,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args: any) => React.createElement(FilledTonalIconButton, args, "favorite"),
};
