/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFilledTonalIconButton} from '@material/web/iconbutton/filled-tonal-icon-button.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FilledTonalIconButtonProps extends WebComponentProps<MdFilledTonalIconButton> {}

export const FilledTonalIconButton = createComponentTyped<MdFilledTonalIconButton, FilledTonalIconButtonProps>({
  displayName: 'FilledTonalIconButton',
  tagName: 'md-filled-tonal-icon-button',
  importPath: '@material/web/iconbutton/filled-tonal-icon-button.js',
  importer: () => import('@material/web/iconbutton/filled-tonal-icon-button.js'),
  
});
