/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdIconButton} from '@material/web/iconbutton/icon-button.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface IconButtonProps extends WebComponentProps<MdIconButton> {}

export const IconButton = createComponentTyped<MdIconButton, IconButtonProps>({
  displayName: 'IconButton',
  tagName: 'md-icon-button',
  importPath: '@material/web/iconbutton/icon-button.js',
  importer: () => import('@material/web/iconbutton/icon-button.js'),
  
});
