/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdOutlinedIconButton} from '@material/web/iconbutton/outlined-icon-button.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface OutlinedIconButtonProps extends WebComponentProps<MdOutlinedIconButton> {}

export const OutlinedIconButton = createComponentTyped<MdOutlinedIconButton, OutlinedIconButtonProps>({
  displayName: 'OutlinedIconButton',
  tagName: 'md-outlined-icon-button',
  importPath: '@material/web/iconbutton/outlined-icon-button.js',
  importer: () => import('@material/web/iconbutton/outlined-icon-button.js'),
  
});
