/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdPrimaryTab} from '@material/web/tabs/primary-tab.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface PrimaryTabProps extends WebComponentProps<MdPrimaryTab> {}

export const PrimaryTab = createComponentTyped<MdPrimaryTab, PrimaryTabProps>({
  displayName: 'PrimaryTab',
  tagName: 'md-primary-tab',
  importPath: '@material/web/tabs/primary-tab.js',
  importer: () => import('@material/web/tabs/primary-tab.js'),
  
});
