/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {PrimaryTab} from './PrimaryTab';

const meta = {
  title: 'tabs/PrimaryTab',
  component: PrimaryTab,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(PrimaryTab, args, "Tab"),
};
