/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type * as React from 'react';
import {forwardRef} from 'react';

import type {MdPrimaryTab} from '@material/web/tabs/primary-tab.js';

import type {WebComponentProps} from '../internal/createComponent';
import {useWebComponent} from '../internal/useWebComponent';

export interface PrimaryTabProps extends WebComponentProps<MdPrimaryTab> {}

export const PrimaryTab = forwardRef<MdPrimaryTab, PrimaryTabProps>(
  function PrimaryTab({children, ...rest}, ref) {
    const {ref: mergedRef, domProps} = useWebComponent<MdPrimaryTab>(
      {
        tagName: 'md-primary-tab',
        importer: () => import('@material/web/tabs/primary-tab.js'),
      },
      rest,
      ref,
    );

    return (
      // eslint-disable-next-line react/no-unknown-property
      <md-primary-tab ref={mergedRef} {...domProps}>
        {children}
      </md-primary-tab>
    );
  },
);
