/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {SecondaryTab} from './SecondaryTab';

const meta = {
  title: 'tabs/SecondaryTab',
  component: SecondaryTab,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(SecondaryTab, args, "Tab"),
};
