/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdSecondaryTab} from '@material/web/tabs/secondary-tab.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface SecondaryTabProps extends WebComponentProps<MdSecondaryTab> {}

export const SecondaryTab = createComponentTyped<MdSecondaryTab, SecondaryTabProps>({
  displayName: 'SecondaryTab',
  tagName: 'md-secondary-tab',
  importPath: '@material/web/tabs/secondary-tab.js',
  importer: () => import('@material/web/tabs/secondary-tab.js'),
  
});
