/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type * as React from 'react';
import {forwardRef} from 'react';

import type {MdSecondaryTab} from '@material/web/tabs/secondary-tab.js';

import type {WebComponentProps} from '../internal/createComponent';
import {useWebComponent} from '../internal/useWebComponent';

export interface SecondaryTabProps extends WebComponentProps<MdSecondaryTab> {}

export const SecondaryTab = forwardRef<MdSecondaryTab, SecondaryTabProps>(
  function SecondaryTab({children, ...rest}, ref) {
    const {ref: mergedRef, domProps} = useWebComponent<MdSecondaryTab>(
      {
        tagName: 'md-secondary-tab',
        importer: () => import('@material/web/tabs/secondary-tab.js'),
      },
      rest,
      ref,
    );

    return (
      // eslint-disable-next-line react/no-unknown-property
      <md-secondary-tab ref={mergedRef} {...domProps}>
        {children}
      </md-secondary-tab>
    );
  },
);
