/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {Tabs} from './Tabs';
import {PrimaryTab as PrimaryTabComponent} from './PrimaryTab';
import {SecondaryTab as SecondaryTabComponent} from './SecondaryTab';
import {Icon} from '../icon';

const CONTENT = ['icon/label', 'icon', 'label'] as const;

const meta = {
  title: 'tabs/Tabs',
  component: Tabs,
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
    controls: {
      include: ['activeTabIndex', 'autoActivate', 'inlineIcon', 'content'],
    },
  },
  argTypes: {
    activeTabIndex: {control: {type: 'number'}},
    autoActivate: {control: {type: 'boolean'}},
    inlineIcon: {control: {type: 'boolean'}},
    content: {control: {type: 'radio'}, options: CONTENT},
    onChange: {table: {disable: true}},
    children: {table: {disable: true}},
  },
};

export default meta;

const PrimaryTab = {
  args: {
    active: true,
    inlineIcon: false,
    content: 'icon/label',
  },
  parameters: {
    layout: 'centered',
    controls: {
      include: ['active', 'inlineIcon', 'content'],
    },
  },
  argTypes: {
    active: {control: {type: 'boolean'}},
    children: {table: {disable: true}},
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  render: (args: any) => {
    const {content, ...tabArgs} = args;

    const [activeTabIndex, setActiveTabIndex] = React.useState<number>(
      typeof args.activeTabIndex === 'number' ? args.activeTabIndex : 0,
    );

    const tabContent = (icon: string, label: string) => {
      const useIcon = content !== 'label';
      const useLabel = content !== 'icon';
      return (
        <>
          {useIcon ? <Icon slot="icon">{icon}</Icon> : null}
          {useLabel ? label : null}
        </>
      );
    };

    const ariaLabelIfIconOnly = (label: string) =>
      content === 'icon' ? {['aria-label']: label} : undefined;

    return (
      <>
         <Tabs
          aria-label="Primary tabs"
          activeTabIndex={activeTabIndex}
          autoActivate={args.autoActivate}
          onChange={(ev) => {
            const target = ev.target as unknown as {activeTabIndex?: number};
            action('change')({activeTabIndex: target.activeTabIndex});
            if (typeof target.activeTabIndex === 'number') setActiveTabIndex(target.activeTabIndex);
          }}
          style={{minWidth: 360}}
        >
          <PrimaryTabComponent
            id="tab-one"
            aria-controls="panel-one"
            inlineIcon={args.inlineIcon}
            {...ariaLabelIfIconOnly('Keyboard')}
          >
            {tabContent('piano', 'Keyboard')}
          </PrimaryTabComponent>
          <PrimaryTabComponent
            id="tab-two"
            aria-controls="panel-two"
            inlineIcon={args.inlineIcon}
            {...ariaLabelIfIconOnly('Guitar')}
          >
            {tabContent('tune', 'Guitar')}
          </PrimaryTabComponent>
          <PrimaryTabComponent
            id="tab-three"
            aria-controls="panel-three"
            inlineIcon={args.inlineIcon}
            {...ariaLabelIfIconOnly('Drums')}
          >
            {tabContent('graphic_eq', 'Drums')}
          </PrimaryTabComponent>
        </Tabs>

        <div
          id="panel-one"
          role="tabpanel"
          aria-labelledby="tab-one"
          hidden={activeTabIndex !== 0}
          style={{padding: 16}}
        >
          Keyboard
        </div>
        <div
          id="panel-two"
          role="tabpanel"
          aria-labelledby="tab-two"
          hidden={activeTabIndex !== 1}
          style={{padding: 16}}
        >
          Guitar
        </div>
        <div
          id="panel-three"
          role="tabpanel"
          aria-labelledby="tab-three"
          hidden={activeTabIndex !== 2}
          style={{padding: 16}}
        >
          Drums
        </div>
      </>
    );
  },
};

export const Default = PrimaryTab;

export const SecondaryTab = {
  args: {
    active: true,
    content: 'icon/label',
  },
  parameters: {
    layout: 'centered',
    controls: {
      include: ['active', 'content'],
    },
  },
  argTypes: {
    active: {control: {type: 'boolean'}},
    children: {table: {disable: true}},
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  render: (args: any) => {
    const {content, ...tabArgs} = args;

    const [activeTabIndex, setActiveTabIndex] = React.useState<number>(
      typeof args.activeTabIndex === 'number' ? args.activeTabIndex : 0,
    );

    const tabContent = (icon: string, label: string) => {
      const useIcon = content !== 'label';
      const useLabel = content !== 'icon';
      return (
        <>
          {useIcon ? <Icon slot="icon">{icon}</Icon> : null}
          {useLabel ? label : null}
        </>
      );
    };

    const ariaLabelIfIconOnly = (label: string) =>
      content === 'icon' ? {['aria-label']: label} : undefined;

    return (
      <>
        <Tabs
          aria-label="Secondary tabs"
          activeTabIndex={activeTabIndex}
          autoActivate={args.autoActivate}
          onChange={(ev) => {
            const target = ev.target as unknown as {activeTabIndex?: number};
            action('change (secondary)')({activeTabIndex: target.activeTabIndex});
            if (typeof target.activeTabIndex === 'number') setActiveTabIndex(target.activeTabIndex);
          }}
          style={{minWidth: 360}}
        >
          <SecondaryTabComponent aria-controls="secondary-one" {...ariaLabelIfIconOnly('Travel')}>
            {tabContent('flight', 'Travel')}
          </SecondaryTabComponent>
          <SecondaryTabComponent aria-controls="secondary-two" {...ariaLabelIfIconOnly('Hotel')}>
            {tabContent('hotel', 'Hotel')}
          </SecondaryTabComponent>
          <SecondaryTabComponent
            aria-controls="secondary-three"
            {...ariaLabelIfIconOnly('Activities')}
          >
            {tabContent('hiking', 'Activities')}
          </SecondaryTabComponent>
        </Tabs>
        <div
          id="panel-one"
          role="tabpanel"
          aria-labelledby="tab-one"
          hidden={activeTabIndex !== 0}
          style={{padding: 16}}
        >
          Travel
        </div>
        <div
          id="panel-two"
          role="tabpanel"
          aria-labelledby="tab-two"
          hidden={activeTabIndex !== 1}
          style={{padding: 16}}
        >
          Hotel
        </div>
        <div
          id="panel-three"
          role="tabpanel"
          aria-labelledby="tab-three"
          hidden={activeTabIndex !== 2}
          style={{padding: 16}}
        >
          Activities
        </div>
      </>
    );
  },
};
