/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type * as React from 'react';
import {forwardRef} from 'react';

import type {MdTabs} from '@material/web/tabs/tabs.js';

import type {WebComponentProps} from '../internal/createComponent';
import {useWebComponent} from '../internal/useWebComponent';

export interface TabsProps extends Omit<WebComponentProps<MdTabs>, 'onChange'> {
  onChange?: (event: Event) => void;
}

export const Tabs = forwardRef<MdTabs, TabsProps>(function Tabs(
  {children, onChange, ...rest},
  ref,
) {
  const {ref: mergedRef, domProps} = useWebComponent<MdTabs>(
    {
      tagName: 'md-tabs',
      importer: () => import('@material/web/tabs/tabs.js'),
      events: {
        change: 'onChange',
      },
    },
    {onChange, ...rest},
    ref,
  );

  return (
    // eslint-disable-next-line react/no-unknown-property
    <md-tabs ref={mergedRef} {...domProps}>
      {children}
    </md-tabs>
  );
});
