/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdTabs} from '@material/web/tabs/tabs.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface TabsProps extends WebComponentProps<MdTabs> {}

export const Tabs = createComponentTyped<MdTabs, TabsProps>({
  displayName: 'Tabs',
  tagName: 'md-tabs',
  importPath: '@material/web/tabs/tabs.js',
  importer: () => import('@material/web/tabs/tabs.js'),
  
});
