/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdCircularProgress} from '@material/web/progress/circular-progress.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface CircularProgressProps extends WebComponentProps<MdCircularProgress> {}

export const CircularProgress = createComponentTyped<MdCircularProgress, CircularProgressProps>({
  displayName: 'CircularProgress',
  tagName: 'md-circular-progress',
  importPath: '@material/web/progress/circular-progress.js',
  importer: () => import('@material/web/progress/circular-progress.js'),
  
});
