/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {CircularProgress} from './CircularProgress';

const meta = {
  title: 'progress/CircularProgress',
  component: CircularProgress,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(CircularProgress, args),
};
