/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {LinearProgress} from './LinearProgress';

const meta = {
  title: 'progress/LinearProgress',
  component: LinearProgress,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(LinearProgress, args),
};
