/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdLinearProgress} from '@material/web/progress/linear-progress.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface LinearProgressProps extends WebComponentProps<MdLinearProgress> {}

export const LinearProgress = createComponentTyped<MdLinearProgress, LinearProgressProps>({
  displayName: 'LinearProgress',
  tagName: 'md-linear-progress',
  importPath: '@material/web/progress/linear-progress.js',
  importer: () => import('@material/web/progress/linear-progress.js'),
  
});
