/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdMenu} from '@material/web/menu/menu.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface MenuProps extends WebComponentProps<MdMenu> {}

export const Menu = createComponentTyped<MdMenu, MenuProps>({
  displayName: 'Menu',
  tagName: 'md-menu',
  importPath: '@material/web/menu/menu.js',
  importer: () => import('@material/web/menu/menu.js'),
  
});
