/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {MenuItem} from './MenuItem';

const meta = {
  title: 'menu/MenuItem',
  component: MenuItem,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(MenuItem, args, "Menu item"),
};
