/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {MenuItem} from './MenuItem';
import {Menu} from './Menu';
import {FilledButton} from '../button';
import {Icon} from '../icon';

const meta = {
  title: 'menu/MenuItem',
  component: MenuItem,
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
    controls: {
      include: ['keepOpen', 'disabled', 'href', 'linkIcon'],
    },
  },
  argTypes: {
    keepOpen: {control: {type: 'boolean'}},
    disabled: {control: {type: 'boolean'}},
    href: {control: {type: 'text'}},
    linkIcon: {name: 'link icon', control: {type: 'text'}},
    onCloseMenu: {table: {disable: true}},
    children: {table: {disable: true}},
  },
};

export default meta;

export const Default = {
  args: {
    keepOpen: true,
    disabled: true,
    href: 'https://google.com',
    linkIcon: 'open_in_new',
  },
  render: (args) => {
    const {linkIcon, ...itemArgs} = args;

    const [open, setOpen] = React.useState(true);
    return (
      <span style={{position: 'relative', display: 'inline-block', minHeight: 220}}>
        <FilledButton id="menu-item-anchor" onClick={() => setOpen((v) => !v)}>
          Toggle menu
        </FilledButton>

        <Menu
          anchor="menu-item-anchor"
          open={open}
          onCloseMenu={(ev) => {
            action('close-menu')(ev);
            setOpen(false);
          }}
          style={{minWidth: 260}}
        >
          <MenuItem
            {...itemArgs}
            target={itemArgs.href ? '_blank' : undefined}
            onCloseMenu={action('close-menu (menu-item)')}
          >
            <div slot="headline">Menu item</div>
            {itemArgs.href ? <Icon slot="end">{linkIcon}</Icon> : null}
          </MenuItem>
        </Menu>
      </span>
    );
  },
};
