/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdMenuItem} from '@material/web/menu/menu-item.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface MenuItemProps extends WebComponentProps<MdMenuItem> {}

export const MenuItem = createComponentTyped<MdMenuItem, MenuItemProps>({
  displayName: 'MenuItem',
  tagName: 'md-menu-item',
  importPath: '@material/web/menu/menu-item.js',
  importer: () => import('@material/web/menu/menu-item.js'),
  
});
