/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdSubMenu} from '@material/web/menu/sub-menu.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface SubMenuProps extends WebComponentProps<MdSubMenu> {}

export const SubMenu = createComponentTyped<MdSubMenu, SubMenuProps>({
  displayName: 'SubMenu',
  tagName: 'md-sub-menu',
  importPath: '@material/web/menu/sub-menu.js',
  importer: () => import('@material/web/menu/sub-menu.js'),
  
});
