/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {SubMenu} from './SubMenu';
import {Menu} from './Menu';
import {MenuItem} from './MenuItem';
import {FilledButton} from '../button';
import {Icon} from '../icon';

const CORNERS = ['start-start', 'start-end', 'end-start', 'end-end'] as const;

const meta = {
  title: 'menu/SubMenu',
  component: SubMenu,
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
    controls: {
      include: [
        'anchorCorner',
        'menuCorner',
        'hoverOpenDelay',
        'hoverCloseDelay',
        'submenuItemIcon',
      ],
    },
  },
  argTypes: {
    anchorCorner: {
      name: 'submenu.anchorCorner',
      control: {type: 'select'},
      options: CORNERS,
    },
    menuCorner: {
      name: 'submenu.menuCorner',
      control: {type: 'select'},
      options: CORNERS,
    },
    hoverOpenDelay: {control: {type: 'number'}},
    hoverCloseDelay: {control: {type: 'number'}},
    submenuItemIcon: {name: 'submenu item icon', control: {type: 'text'}},
    onDeactivateItems: {table: {disable: true}},
    onRequestActivation: {table: {disable: true}},
    onDeactivateTypeahead: {table: {disable: true}},
    onActivateTypeahead: {table: {disable: true}},
    children: {table: {disable: true}},
  },
};

export default meta;

export const Default = {
  args: {
    anchorCorner: 'start-end',
    menuCorner: 'start-start',
    hoverOpenDelay: 400,
    hoverCloseDelay: 400,
    submenuItemIcon: 'navigate_next',
  },
  render: (args) => {
    const {
      anchorCorner,
      menuCorner,
      submenuItemIcon,
      hoverOpenDelay,
      hoverCloseDelay,
    } = args;

    const [open, setOpen] = React.useState(true);
    return (
      <span style={{position: 'relative', display: 'inline-block', minHeight: 300}}>
        <FilledButton id="submenu-anchor" onClick={() => setOpen((v) => !v)}>
          Menu with submenus
        </FilledButton>

        <Menu
          anchor="submenu-anchor"
          open={open}
          hasOverflow
          onCloseMenu={() => setOpen(false)}
          style={{minWidth: 280}}
        >
          <SubMenu
            anchorCorner={anchorCorner}
            menuCorner={menuCorner}
            hoverOpenDelay={hoverOpenDelay}
            hoverCloseDelay={hoverCloseDelay}
            onDeactivateItems={action('deactivate-items')}
            onRequestActivation={action('request-activation')}
            onDeactivateTypeahead={action('deactivate-typeahead')}
            onActivateTypeahead={action('activate-typeahead')}
          >
            <MenuItem slot="item">
              <div slot="headline">Fruits with A</div>
              <Icon slot="end">{submenuItemIcon}</Icon>
            </MenuItem>

            <Menu slot="menu">
              <MenuItem>
                <div slot="headline">Apricot</div>
              </MenuItem>
              <MenuItem>
                <div slot="headline">Avocado</div>
              </MenuItem>

              <SubMenu menuCorner={menuCorner} anchorCorner={anchorCorner}>
                <MenuItem slot="item">
                  <Icon slot="start">arrow_left</Icon>
                  <div slot="headline">Apples</div>
                </MenuItem>
                <Menu slot="menu">
                  <MenuItem>
                    <div slot="headline">Fuji</div>
                  </MenuItem>
                  <MenuItem>
                    <div slot="headline" style={{whiteSpace: 'nowrap'}}>
                      Granny Smith
                    </div>
                  </MenuItem>
                  <MenuItem>
                    <div slot="headline" style={{whiteSpace: 'nowrap'}}>
                      Red Delicious
                    </div>
                  </MenuItem>
                </Menu>
              </SubMenu>
            </Menu>
          </SubMenu>

          <MenuItem>
            <div slot="headline">Banana</div>
          </MenuItem>
          <MenuItem>
            <div slot="headline">Cucumber</div>
          </MenuItem>
        </Menu>
      </span>
    );
  },
};
