/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {SubMenu} from './SubMenu';

const meta = {
  title: 'menu/SubMenu',
  component: SubMenu,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(SubMenu, args, "Submenu"),
};
