/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdRadio} from '@material/web/radio/radio.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface RadioProps extends Omit<WebComponentProps<MdRadio>, 'onChange' | 'onInput'> {
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
}

export const Radio = createComponentTyped<MdRadio, RadioProps>({
  displayName: 'Radio',
  tagName: 'md-radio',
  importPath: '@material/web/radio/radio.js',
  importer: () => import('@material/web/radio/radio.js'),
  events: {
  "change": "onChange",
  "input": "onInput"
},
});
