/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {FilledField} from './FilledField';
import {Icon} from '../icon';

const meta = {
  title: 'field/FilledField',
  component: FilledField,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => (
    <FilledField
      {...args}
      label="Label"
      supportingText="Supporting text"
      style={{width: 280}}
      hasStart
      hasEnd
    >
      <Icon slot="start">search</Icon>
      <input aria-label="Filled field input" />
      <Icon slot="end">event</Icon>
    </FilledField>
  ),
};
