/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFilledField} from '@material/web/field/filled-field.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FilledFieldProps extends WebComponentProps<MdFilledField> {}

export const FilledField = createComponentTyped<MdFilledField, FilledFieldProps>({
  displayName: 'FilledField',
  tagName: 'md-filled-field',
  importPath: '@material/web/field/filled-field.js',
  importer: () => import('@material/web/field/filled-field.js'),
  
});
