/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {FilledField} from './FilledField';

const meta = {
  title: 'field/FilledField',
  component: FilledField,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args: any) => React.createElement(FilledField, args, "Field"),
};
