/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {OutlinedField} from './OutlinedField';
import {Icon} from '../icon';

const meta = {
  title: 'field/OutlinedField',
  component: OutlinedField,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => (
    <OutlinedField
      {...args}
      label="Label"
      supportingText="Supporting text"
      style={{width: 280}}
      hasStart
      hasEnd
    >
      <div id="description" slot="aria-describedby" hidden />
      <Icon slot="start">search</Icon>
      <input aria-label="Outlined field input" aria-describedby="description" />
      <Icon slot="end">event</Icon>
    </OutlinedField>
  ),
};
