/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdOutlinedField} from '@material/web/field/outlined-field.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface OutlinedFieldProps extends WebComponentProps<MdOutlinedField> {}

export const OutlinedField = createComponentTyped<MdOutlinedField, OutlinedFieldProps>({
  displayName: 'OutlinedField',
  tagName: 'md-outlined-field',
  importPath: '@material/web/field/outlined-field.js',
  importer: () => import('@material/web/field/outlined-field.js'),
  
});
