/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {Badge} from './Badge';

const meta = {
  title: 'labs/Badge',
  component: Badge,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => (
    <div style={{position: 'relative', width: 48, height: 48}}>
      <div
        style={{
          width: 48,
          height: 48,
          borderRadius: 12,
          background: 'var(--md-sys-color-secondary-container)',
          outline: '1px solid var(--md-sys-color-outline)',
        }}
      />
      <Badge {...args} value="1" style={{position: 'absolute', top: 0, right: 0}} />
    </div>
  ),
};
