/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdBadge} from '@material/web/labs/badge/badge.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface BadgeProps extends WebComponentProps<MdBadge> {}

export const Badge = createComponentTyped<MdBadge, BadgeProps>({
  displayName: 'Badge',
  tagName: 'md-badge',
  importPath: '@material/web/labs/badge/badge.js',
  importer: () => import('@material/web/labs/badge/badge.js'),
  
});
