/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {Badge} from './Badge';

const meta = {
  title: 'labs/Badge',
  component: Badge,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args: any) => React.createElement(Badge, args, "1"),
};
