/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {ElevatedCard} from './ElevatedCard';

const meta = {
  title: 'labs/ElevatedCard',
  component: ElevatedCard,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(ElevatedCard, args, "Card"),
};
