/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdElevatedCard} from '@material/web/labs/card/elevated-card.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface ElevatedCardProps extends WebComponentProps<MdElevatedCard> {}

export const ElevatedCard = createComponentTyped<MdElevatedCard, ElevatedCardProps>({
  displayName: 'ElevatedCard',
  tagName: 'md-elevated-card',
  importPath: '@material/web/labs/card/elevated-card.js',
  importer: () => import('@material/web/labs/card/elevated-card.js'),
  
});
