/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFilledCard} from '@material/web/labs/card/filled-card.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FilledCardProps extends WebComponentProps<MdFilledCard> {}

export const FilledCard = createComponentTyped<MdFilledCard, FilledCardProps>({
  displayName: 'FilledCard',
  tagName: 'md-filled-card',
  importPath: '@material/web/labs/card/filled-card.js',
  importer: () => import('@material/web/labs/card/filled-card.js'),
  
});
