/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {Item} from './Item';
import {Icon} from '../icon';

const meta = {
  title: 'labs/Item',
  component: Item,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => (
    <div style={{width: 360}}>
      <Item {...args}>
        <Icon slot="start">image</Icon>
        <div slot="headline">Headline</div>
        <div slot="supporting-text">Supporting text</div>
        <div slot="trailing-supporting-text">Trailing</div>
        <Icon slot="end">chevron_right</Icon>
      </Item>
    </div>
  ),
};
