/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdItem} from '@material/web/labs/item/item.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface ItemProps extends WebComponentProps<MdItem> {}

export const Item = createComponentTyped<MdItem, ItemProps>({
  displayName: 'Item',
  tagName: 'md-item',
  importPath: '@material/web/labs/item/item.js',
  importer: () => import('@material/web/labs/item/item.js'),
  
});
