/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdNavigationTab} from '@material/web/labs/navigationtab/navigation-tab.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface NavigationTabProps extends Omit<WebComponentProps<MdNavigationTab>, 'onInteraction'> {
  onInteraction?: (event: Event) => void;
}

export const NavigationTab = createComponentTyped<MdNavigationTab, NavigationTabProps>({
  displayName: 'NavigationTab',
  tagName: 'md-navigation-tab',
  importPath: '@material/web/labs/navigationtab/navigation-tab.js',
  importer: () => import('@material/web/labs/navigationtab/navigation-tab.js'),
  events: {
  "navigation-tab-interaction": "onInteraction"
},
});
