/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {NavigationTab} from './NavigationTab';

const meta = {
  title: 'labs/NavigationTab',
  component: NavigationTab,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onInteraction: action('navigation-tab-interaction'),
  },
  render: (args) => React.createElement(NavigationTab, args, "Tab"),
};
