/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {NavigationBar} from './NavigationBar';

const meta = {
  title: 'labs/NavigationBar',
  component: NavigationBar,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onActivated: action('navigation-bar-activated'),
  },
  render: (args) => React.createElement(NavigationBar, args, "NavigationBar"),
};
