/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {NavigationDrawer} from './NavigationDrawer';

const meta = {
  title: 'labs/NavigationDrawer',
  component: NavigationDrawer,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onChanged: action('navigation-drawer-changed'),
  },
  render: (args) => React.createElement(NavigationDrawer, args, "NavigationDrawer"),
};
