/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {NavigationDrawerModal} from './NavigationDrawerModal';

const meta = {
  title: 'labs/NavigationDrawerModal',
  component: NavigationDrawerModal,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onChanged: action('navigation-drawer-changed'),
  },
  render: (args) => React.createElement(NavigationDrawerModal, args, "NavigationDrawerModal"),
};
