/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdNavigationDrawer} from '@material/web/labs/navigationdrawer/navigation-drawer.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface NavigationDrawerProps extends Omit<WebComponentProps<MdNavigationDrawer>, 'onChanged'> {
  onChanged?: (event: Event) => void;
}

export const NavigationDrawer = createComponentTyped<MdNavigationDrawer, NavigationDrawerProps>({
  displayName: 'NavigationDrawer',
  tagName: 'md-navigation-drawer',
  importPath: '@material/web/labs/navigationdrawer/navigation-drawer.js',
  importer: () => import('@material/web/labs/navigationdrawer/navigation-drawer.js'),
  events: {
  "navigation-drawer-changed": "onChanged"
},
});
