/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdNavigationBar} from '@material/web/labs/navigationbar/navigation-bar.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface NavigationBarProps extends Omit<WebComponentProps<MdNavigationBar>, 'onActivated'> {
  onActivated?: (event: Event) => void;
}

export const NavigationBar = createComponentTyped<MdNavigationBar, NavigationBarProps>({
  displayName: 'NavigationBar',
  tagName: 'md-navigation-bar',
  importPath: '@material/web/labs/navigationbar/navigation-bar.js',
  importer: () => import('@material/web/labs/navigationbar/navigation-bar.js'),
  events: {
  "navigation-bar-activated": "onActivated"
},
});
