/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdNavigationDrawerModal} from '@material/web/labs/navigationdrawer/navigation-drawer-modal.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface NavigationDrawerModalProps extends Omit<WebComponentProps<MdNavigationDrawerModal>, 'onChanged'> {
  onChanged?: (event: Event) => void;
}

export const NavigationDrawerModal = createComponentTyped<MdNavigationDrawerModal, NavigationDrawerModalProps>({
  displayName: 'NavigationDrawerModal',
  tagName: 'md-navigation-drawer-modal',
  importPath: '@material/web/labs/navigationdrawer/navigation-drawer-modal.js',
  importer: () => import('@material/web/labs/navigationdrawer/navigation-drawer-modal.js'),
  events: {
  "navigation-drawer-changed": "onChanged"
},
});
