/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {OutlinedSegmentedButtonSet} from './OutlinedSegmentedButtonSet';

const meta = {
  title: 'labs/OutlinedSegmentedButtonSet',
  component: OutlinedSegmentedButtonSet,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onSelection: action('segmented-button-set-selection'),
  },
  render: (args) => React.createElement(OutlinedSegmentedButtonSet, args, "OutlinedSegmentedButtonSet"),
};
