/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type * as React from 'react';
import {forwardRef} from 'react';

import type {MdOutlinedCard} from '@material/web/labs/card/outlined-card.js';

import type {WebComponentProps} from '../internal/createComponent';
import {useWebComponent} from '../internal/useWebComponent';

export interface OutlinedCardProps extends WebComponentProps<MdOutlinedCard> {}

export const OutlinedCard = forwardRef<MdOutlinedCard, OutlinedCardProps>(
  function OutlinedCard({children, ...rest}, ref) {
    const {ref: mergedRef, domProps} = useWebComponent<MdOutlinedCard>(
      {
        tagName: 'md-outlined-card',
        importer: () => import('@material/web/labs/card/outlined-card.js'),
      },
      rest,
      ref,
    );

    return (
      // eslint-disable-next-line react/no-unknown-property
      <md-outlined-card ref={mergedRef} {...domProps}>
        {children}
      </md-outlined-card>
    );
  },
);
