/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type * as React from 'react';
import {forwardRef} from 'react';

import type {MdOutlinedSegmentedButtonSet} from '@material/web/labs/segmentedbuttonset/outlined-segmented-button-set.js';

import type {WebComponentProps} from '../internal/createComponent';
import {useWebComponent} from '../internal/useWebComponent';

export interface OutlinedSegmentedButtonSetProps
  extends Omit<WebComponentProps<MdOutlinedSegmentedButtonSet>, 'onSelection'> {
  onSelection?: (event: Event) => void;
}

export const OutlinedSegmentedButtonSet = forwardRef<
  MdOutlinedSegmentedButtonSet,
  OutlinedSegmentedButtonSetProps
>(function OutlinedSegmentedButtonSet(
  {children, onSelection, ...rest},
  ref,
) {
  const {ref: mergedRef, domProps} = useWebComponent<MdOutlinedSegmentedButtonSet>(
    {
      tagName: 'md-outlined-segmented-button-set',
      importer: () => import('@material/web/labs/segmentedbuttonset/outlined-segmented-button-set.js'),
      events: {'segmented-button-set-selection': 'onSelection'},
    },
    {onSelection, ...rest},
    ref,
  );

  return (
    // eslint-disable-next-line react/no-unknown-property
    <md-outlined-segmented-button-set ref={mergedRef} {...domProps}>
      {children}
    </md-outlined-segmented-button-set>
  );
});
