/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdOutlinedCard} from '@material/web/labs/card/outlined-card.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface OutlinedCardProps extends WebComponentProps<MdOutlinedCard> {}

export const OutlinedCard = createComponentTyped<MdOutlinedCard, OutlinedCardProps>({
  displayName: 'OutlinedCard',
  tagName: 'md-outlined-card',
  importPath: '@material/web/labs/card/outlined-card.js',
  importer: () => import('@material/web/labs/card/outlined-card.js'),
  
});
