/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdOutlinedSegmentedButton} from '@material/web/labs/segmentedbutton/outlined-segmented-button.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface OutlinedSegmentedButtonProps extends WebComponentProps<MdOutlinedSegmentedButton> {}

export const OutlinedSegmentedButton = createComponentTyped<MdOutlinedSegmentedButton, OutlinedSegmentedButtonProps>({
  displayName: 'OutlinedSegmentedButton',
  tagName: 'md-outlined-segmented-button',
  importPath: '@material/web/labs/segmentedbutton/outlined-segmented-button.js',
  importer: () => import('@material/web/labs/segmentedbutton/outlined-segmented-button.js'),
  
});
