/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {OutlinedSegmentedButton} from './OutlinedSegmentedButton';

const meta = {
  title: 'labs/OutlinedSegmentedButton',
  component: OutlinedSegmentedButton,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(OutlinedSegmentedButton, args, "Option"),
};
