/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {OutlinedSegmentedButtonSet} from './OutlinedSegmentedButtonSet';
import {OutlinedSegmentedButton} from './OutlinedSegmentedButton';
import {Icon} from '../icon';

const meta = {
  title: 'labs/OutlinedSegmentedButtonSet',
  component: OutlinedSegmentedButtonSet,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onSelection: action('segmented-button-set-selection'),
  },
  render: (args) => (
    <div style={{width: 325}}>
      <OutlinedSegmentedButtonSet {...args}>
        <OutlinedSegmentedButton label="Enabled">
          <Icon slot="icon">grade</Icon>
        </OutlinedSegmentedButton>
        <OutlinedSegmentedButton selected label="Selected">
          <Icon slot="icon">favorite</Icon>
        </OutlinedSegmentedButton>
        <OutlinedSegmentedButton label="Enabled">
          <Icon slot="icon">change_history</Icon>
        </OutlinedSegmentedButton>
      </OutlinedSegmentedButtonSet>
    </div>
  ),
};
