/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdOutlinedSegmentedButtonSet} from '@material/web/labs/segmentedbuttonset/outlined-segmented-button-set.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface OutlinedSegmentedButtonSetProps extends Omit<WebComponentProps<MdOutlinedSegmentedButtonSet>, 'onSelection'> {
  onSelection?: (event: Event) => void;
}

export const OutlinedSegmentedButtonSet = createComponentTyped<MdOutlinedSegmentedButtonSet, OutlinedSegmentedButtonSetProps>({
  displayName: 'OutlinedSegmentedButtonSet',
  tagName: 'md-outlined-segmented-button-set',
  importPath: '@material/web/labs/segmentedbuttonset/outlined-segmented-button-set.js',
  importer: () => import('@material/web/labs/segmentedbuttonset/outlined-segmented-button-set.js'),
  events: {
  "segmented-button-set-selection": "onSelection"
},
});
