/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {OutlinedCard} from './OutlinedCard';

const meta = {
  title: 'labs/OutlinedCard',
  component: OutlinedCard,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(OutlinedCard, args, "Card"),
};
