/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {OutlinedSegmentedButton} from './OutlinedSegmentedButton';
import {OutlinedSegmentedButtonSet} from './OutlinedSegmentedButtonSet';

const meta = {
  title: 'labs/OutlinedSegmentedButton',
  component: OutlinedSegmentedButton,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => (
    <div style={{width: 325}}>
      <OutlinedSegmentedButtonSet>
        <OutlinedSegmentedButton {...args} selected label="Option" />
        <OutlinedSegmentedButton label="Second" />
      </OutlinedSegmentedButtonSet>
    </div>
  ),
};
