/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type * as React from 'react';
import {forwardRef} from 'react';

import type {MdOutlinedSegmentedButton} from '@material/web/labs/segmentedbutton/outlined-segmented-button.js';

import type {WebComponentProps} from '../internal/createComponent';
import {useWebComponent} from '../internal/useWebComponent';

export interface OutlinedSegmentedButtonProps
  extends WebComponentProps<MdOutlinedSegmentedButton> {}

export const OutlinedSegmentedButton = forwardRef<
  MdOutlinedSegmentedButton,
  OutlinedSegmentedButtonProps
>(function OutlinedSegmentedButton({children, ...rest}, ref) {
  const {ref: mergedRef, domProps} = useWebComponent<MdOutlinedSegmentedButton>(
    {
      tagName: 'md-outlined-segmented-button',
      importer: () => import('@material/web/labs/segmentedbutton/outlined-segmented-button.js'),
    },
    rest,
    ref,
  );

  return (
    // eslint-disable-next-line react/no-unknown-property
    <md-outlined-segmented-button ref={mergedRef} {...domProps}>
      {children}
    </md-outlined-segmented-button>
  );
});
