/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdElevation} from '@material/web/elevation/elevation.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface ElevationProps extends WebComponentProps<MdElevation> {}

export const Elevation = createComponentTyped<MdElevation, ElevationProps>({
  displayName: 'Elevation',
  tagName: 'md-elevation',
  importPath: '@material/web/elevation/elevation.js',
  importer: () => import('@material/web/elevation/elevation.js'),
  
});
