/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {Elevation} from './Elevation';

const meta = {
  title: 'elevation/Elevation',
  component: Elevation,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args: any) => React.createElement(Elevation, args),
};
