/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {Elevation} from './Elevation';

const meta = {
  title: 'elevation/Elevation',
  component: Elevation,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => (
    <div
      style={{
        alignItems: 'center',
        background: 'var(--md-sys-color-primary-container)',
        border: '1px solid var(--md-sys-color-outline)',
        borderRadius: 16,
        color: 'var(--md-sys-color-on-primary-container)',
        display: 'flex',
        height: 96,
        justifyContent: 'center',
        position: 'relative',
        width: 160,
        ['--md-elevation-level' as any]: 2,
      }}
    >
      Level 2
      <Elevation {...args} />
    </div>
  ),
};
