/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdDivider} from '@material/web/divider/divider.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface DividerProps extends WebComponentProps<MdDivider> {}

export const Divider = createComponentTyped<MdDivider, DividerProps>({
  displayName: 'Divider',
  tagName: 'md-divider',
  importPath: '@material/web/divider/divider.js',
  importer: () => import('@material/web/divider/divider.js'),
  
});
