/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdFilledTextField} from '@material/web/textfield/filled-text-field.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface FilledTextFieldProps extends Omit<WebComponentProps<MdFilledTextField>, 'onChange' | 'onInput'> {
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
}

export const FilledTextField = createComponentTyped<MdFilledTextField, FilledTextFieldProps>({
  displayName: 'FilledTextField',
  tagName: 'md-filled-text-field',
  importPath: '@material/web/textfield/filled-text-field.js',
  importer: () => import('@material/web/textfield/filled-text-field.js'),
  events: {
  "change": "onChange",
  "input": "onInput"
},
});
