/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdOutlinedTextField} from '@material/web/textfield/outlined-text-field.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface OutlinedTextFieldProps extends Omit<WebComponentProps<MdOutlinedTextField>, 'onChange' | 'onInput'> {
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
}

export const OutlinedTextField = createComponentTyped<MdOutlinedTextField, OutlinedTextFieldProps>({
  displayName: 'OutlinedTextField',
  tagName: 'md-outlined-text-field',
  importPath: '@material/web/textfield/outlined-text-field.js',
  importer: () => import('@material/web/textfield/outlined-text-field.js'),
  events: {
  "change": "onChange",
  "input": "onInput"
},
});
