/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {NavigationTab} from './NavigationTab';
import {NavigationBar} from './NavigationBar';
import {Icon} from '../icon';

const meta = {
  title: 'Navigation/NavigationTab',
  component: NavigationTab,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onInteraction: action('navigation-tab-interaction'),
  },
  render: (args) => (
    <div style={{width: 400}}>
      <NavigationBar activeIndex={0}>
        <NavigationTab {...args} label="Tab" showBadge badgeValue="3">
          <Icon slot="active-icon">star</Icon>
          <Icon slot="inactive-icon">star</Icon>
        </NavigationTab>
      </NavigationBar>
    </div>
  ),
};
