/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {NavigationDrawerModal} from './NavigationDrawerModal';
import {FilledButton} from '../button';
import {NavigationDrawerItem} from './NavigationDrawerItem';
import {Icon} from '../icon';

const meta = {
  title: 'Navigation/NavigationDrawerModal',
  component: NavigationDrawerModal,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onChanged: action('navigation-drawer-changed'),
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  render: (args: any) => {
    const [opened, setOpened] = React.useState(true);
    return (
      <div style={{display: 'grid', gap: 12, justifyItems: 'start'}}>
        <FilledButton onClick={() => setOpened((v) => !v)}>
          Toggle modal drawer
        </FilledButton>
        <NavigationDrawerModal
          {...args}
          opened={opened}
          pivot="start"
          onChanged={(ev) => {
            args.onChanged?.(ev.detail);
            setOpened(ev.detail.opened);
          }}
          header={<div style={{padding: 8, fontWeight: 600}}>Menu</div>}
          defaultValue="inbox"
          onValueChange={() => setOpened(false)}
        >
          <NavigationDrawerItem value="inbox" label="Inbox" icon={<Icon>inbox</Icon>} supporting="24" />
          <NavigationDrawerItem value="outbox" label="Outbox" icon={<Icon>send</Icon>} />
          <NavigationDrawerItem value="favorites" label="Favorites" icon={<Icon>favorite</Icon>} />
          <NavigationDrawerItem value="trash" label="Trash" icon={<Icon>delete</Icon>} />
        </NavigationDrawerModal>
      </div>
    );
  },
};
