/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {NavigationBar} from './NavigationBar';
import {NavigationBarItem} from './NavigationBarItem';
import {Icon} from '../icon';

const meta = {
  title: 'Navigation/NavigationBar',
  component: NavigationBar,
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
    controls: {
      include: ['variant', 'activeIndex', 'hideInactiveLabels'],
    },
  },
  argTypes: {
    variant: {control: {type: 'radio'}, options: ['vertical', 'horizontal']},
    activeIndex: {control: {type: 'number'}},
    hideInactiveLabels: {control: {type: 'boolean'}},
    onActivated: {table: {disable: true}},
    children: {table: {disable: true}},
  },
};

export default meta;

export const Default = {
  args: {
    variant: 'vertical',
    activeIndex: 1,
    hideInactiveLabels: false,
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  render: (args: any) => {
    const [activeIndex, setActiveIndex] = React.useState<number>(args.activeIndex ?? 0);
    React.useEffect(() => {
      if (typeof args.activeIndex === 'number') setActiveIndex(args.activeIndex);
    }, [args.activeIndex]);

    return (
      <div style={{width: 520}}>
        <NavigationBar
          variant={args.variant}
          hideInactiveLabels={args.hideInactiveLabels}
          activeIndex={activeIndex}
          onActivated={(ev) => {
            action('navigation-bar-activated')(ev.detail);
            setActiveIndex(ev.detail.activeIndex);
          }}
        >
          <NavigationBarItem
            label="Home"
            icon={<Icon>home</Icon>}
            activeIcon={<Icon>home</Icon>}
            badge={<span style={{marginLeft: 2, fontSize: 10, opacity: 0.9}}>1</span>}
          />
          <NavigationBarItem label="Search" icon={<Icon>search</Icon>} />
          <NavigationBarItem label="Library" icon={<Icon>library_books</Icon>} />
          <NavigationBarItem label="Profile" icon={<Icon>person</Icon>} />
        </NavigationBar>
      </div>
    );
  },
};
