/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {NavigationDrawer} from './NavigationDrawer';
import {FilledButton} from '../button';
import {NavigationDrawerItem} from './NavigationDrawerItem';
import {Icon} from '../icon';

const meta = {
  title: 'Navigation/NavigationDrawer',
  component: NavigationDrawer,
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
    controls: {
      include: ['variant', 'pivot', 'opened', 'value'],
    },
  },
  argTypes: {
    variant: {control: {type: 'radio'}, options: ['standard', 'modal']},
    pivot: {control: {type: 'radio'}, options: ['start', 'end']},
    opened: {control: {type: 'boolean'}},
    value: {control: {type: 'radio'}, options: ['inbox', 'outbox', 'favorites', 'trash']},
    onChanged: {table: {disable: true}},
    onValueChange: {table: {disable: true}},
    header: {table: {disable: true}},
    children: {table: {disable: true}},
  },
};

export default meta;

export const Default = {
  args: {
    variant: 'standard',
    pivot: 'start',
    opened: true,
    value: 'inbox',
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  render: (args: any) => {
    const [opened, setOpened] = React.useState(Boolean(args.opened));
    const [value, setValue] = React.useState<string>(args.value);

    React.useEffect(() => {
      setOpened(Boolean(args.opened));
    }, [args.opened]);

    React.useEffect(() => {
      if (typeof args.value === 'string') setValue(args.value);
    }, [args.value]);

    return (
      <div style={{display: 'grid', gap: 12, justifyItems: 'start'}}>
        <FilledButton onClick={() => setOpened((v) => !v)}>
          Toggle drawer
        </FilledButton>
        <NavigationDrawer
          variant={args.variant}
          pivot={args.pivot}
          opened={opened}
          onChanged={(ev) => {
            action('navigation-drawer-changed')(ev.detail);
          }}
          value={value}
          onValueChange={(next) => {
            action('navigation-drawer-item-selected')(next);
            setValue(next);
            if (args.variant === 'modal') setOpened(false);
          }}
          header={
            <div style={{padding: 8}}>
              <div style={{fontSize: 16, fontWeight: 600}}>Mail</div>
              <div style={{fontSize: 12, opacity: 0.7}}>Navigation drawer</div>
            </div>
          }
        >
          <NavigationDrawerItem
            value="inbox"
            label="Inbox"
            icon={<Icon>inbox</Icon>}
            supporting="24"
          />
          <NavigationDrawerItem value="outbox" label="Outbox" icon={<Icon>send</Icon>} />
          <NavigationDrawerItem value="favorites" label="Favorites" icon={<Icon>favorite</Icon>} />
          <NavigationDrawerItem value="trash" label="Trash" icon={<Icon>delete</Icon>} />
        </NavigationDrawer>
      </div>
    );
  },
};
