import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Components',
      link: {type: 'doc', id: 'components/index'},
      items: [{type: 'autogenerated', dirName: 'components'}],
    },
    {
      type: 'category',
      label: 'Utilities',
      link: {type: 'doc', id: 'utilities/index'},
      items: [{type: 'autogenerated', dirName: 'utilities'}],
    },
  ],
};

export default sidebars;
