/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdListItem} from '@material/web/list/list-item.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface ListItemProps extends WebComponentProps<MdListItem> {}

export const ListItem = createComponentTyped<MdListItem, ListItemProps>({
  displayName: 'ListItem',
  tagName: 'md-list-item',
  importPath: '@material/web/list/list-item.js',
  importer: () => import('@material/web/list/list-item.js'),
  
});
