/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import type {MdList} from '@material/web/list/list.js';

import {createComponentTyped, type WebComponentProps} from '../internal/createComponent';

export interface ListProps extends WebComponentProps<MdList> {}

export const List = createComponentTyped<MdList, ListProps>({
  displayName: 'List',
  tagName: 'md-list',
  importPath: '@material/web/list/list.js',
  importer: () => import('@material/web/list/list.js'),
  
});
