/**
 * This file is generated by scripts/generate-wrappers.mjs
 */

import React from 'react';
import {action} from '@storybook/addon-actions';

import {ListItem} from './ListItem';

const meta = {
  title: 'list/ListItem',
  component: ListItem,
  tags: ['autodocs'],
  parameters: {layout: 'centered'},
};

export default meta;

export const Default = {
  args: {
    onClick: action('click'),
  },
  render: (args) => React.createElement(ListItem, args, "List item"),
};
